policy:
  - template: [bug_mermaid.yml]
    section:
      - id: [topic_documentation]
        block-list: ['No']
        label:
          - name: 'documentation'
            keys: ['Yes']

      - id: [diagrams]
        block-list: ['None']
        label:
          - name: 'diagram: c4'
            keys: ['C4 diagram']
          - name: 'diagram: class'
            keys: ['Class diagram']
          - name: 'diagram: er'
            keys: ['Entity Relationship (ER) diagram']
          - name: 'diagram: flowchart'
            keys: ['Flowchart']
          - name: 'diagram: gantt'
            keys: ['Gantt']
          - name: 'diagram: git'
            keys: ['Git']
          - name: 'diagram-pie'
            keys: ['Pie']
          - name: diagram-requirements
            keys: ['Requirements']
          - name: diagram-sequence
            keys: ['Sequence']
          - name: diagram-state
            keys: ['State diagram']
          - name: diagram-user-journey
            keys: ['User journey']
          - name: diagram-all
            keys: ['All diagrams']
