
name: Mermaid Bug form
description: Create a bug report to help us improve
title: "[Bug]: "
labels: ["mermaid", "bug", "triage"]
body:
- type: markdown
  attributes:
    value: |-
      ## Before you submit...
      We like to help you, but in order to do that should you make a few things first:

      - Use a clear and concise title
      - Fill out the text fields with as much detail as possible.
      - Never be shy to give us screenshots and/or code samples. It will help!
- type: textarea
  attributes:
    label: Description 
    description: Give a clear and concise description of what the bug is.
    placeholder: When I do ... does ... happen.
  validations:
    required: true
    
- type: dropdown
  id: topic_documentation
  attributes:
    label: "Does the problem also involve the documentation?"
    options:
      - 'No'
      - 'Yes'
  validations:
    required: true

- type: dropdown
  id: topic_diagrams
  attributes:
    label: "Please check any and all diagrams invovled."
    options:
      - label: 'C4 diagram'
      - label: 'Class diagram'
      - label: 'Entity Relationship (ER) diagram'
      - label: 'Flowchart'
      - label: 'Gantt'
      - label: 'Git'
      - label: 'Pie'
      - label: 'Requirements'
      - label: 'Sequence'
      - label: 'State diagram'
      - label: 'User Journey diagram'
      - label: 'All diagrams'
        
- type: textarea
  attributes:
    label: Steps to reproduce
    description: Give a step-by-step example on how to reproduce the bug.
    placeholder: |-
      1. Do this
      2. Do that
      3. ...
      4. Bug!
  validations:
    required: true
- type: textarea
  attributes:
    label: Screenshots
    description: If applicable, add screenshots to help explain your issue.
- type: textarea
  attributes:
    label: Code Sample
    description: |-
      If applicable, add the code sample or a link to the [Live Editor](https://mermaid.live).
      Any text pasted here will be rendered as a Code block.
    render: text
- type: textarea
  attributes:
    label: Setup
    description: |-
      Please fill out the below info.
      Note that you only need to fill out one and not both sections.
    value: |-
      **Desktop**

      - OS and Version: [Windows, Linux, Mac, ...]
      - Browser and Version: [Chrome, Edge, Firefox]

      **Smartphone**

      - Device: [Samsung, iPhone, ...]
      - OS and Version: [Android, iOS, ...]
      - Browser and Version: [Chrome, Safari, ...]
- type: textarea
  attributes:
    label: Additional Context
    description: Anything else to add?
