name: Issue labeler
on:
  issues:
    types: [ opened, edited ]

jobs:
  label-component:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Parse issue form
        uses: stefanbuck/github-issue-parser@v2
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/bug_mermaid.yml

      - name: Set documentation label if topic_documentation = 'Yes'
        uses: redhat-plumbers-in-action/advanced-issue-labeler@latest
        with:
          issue-form: ${{ steps.issue-parser.outputs.jsonString }}
          section: topic_documentation
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set diagram type label from diagrams values
        uses: redhat-plumbers-in-action/advanced-issue-labeler@latest
        with:
          issue-form: ${{ steps.issue-parser.outputs.jsonString }}
          section: diagrams
          token: ${{ secrets.GITHUB_TOKEN }}
